#50/feat/il8n
ohtutraininghub/traininghub pull request #101
Opened 2023-10-05 07:04 UTC by mmoila

-Internationalization support 

Closes #50

2023-10-09 10:39 UTC, joonas-a commented on src/components/ConfirmCard/index.tsx
> +import { useDictionary } from '@/lib/i18n/hooks';
We should stick to using either the ts path alias @i18n (defined in tsconfig, more compact) or just plain @

2023-10-10 20:30 UTC, DeeCaaD approved these changes

2023-10-10 20:56 UTC, DeeCaaD requested changes

2023-10-10 20:56 UTC, DeeCaaD commented on src/components/CourseCard/CourseCard.tsx
> +          {dict.CourseCard.signups.replace('{x}', String(course.maxStudents))}
This requires some better way, as it's common to have variables in string

Java has String.format(string, value1, value2) -> perhaps there is equivalent in JavaScript

2023-10-10 21:11 UTC, DeeCaaD commented
System to support multiple files should also be there before merging. Otherwise this becomes a mess too quickly

2023-10-17 15:39 UTC, closed without merging