Functionality for fetching data for the csv file
ohtutraininghub/traininghub pull request #574
Opened 2024-04-11 14:34 UTC by laurelcrelia

Created prisma query that fetches training name, the trainer name, participants (name, country and title) and date of the training. Data is filtered by fromDate and toDate.  Also created api/course/statistics GET route that uses URL searchParameters fromDate and toDate.

2024-04-12 11:17 UTC, erjavaskivuori requested changes
Commented about one error message and about tests that could be added. Otherwise everything is looking good!

2024-04-12 11:17 UTC, erjavaskivuori commented on src/app/api/course/statistics/route.ts
> +        message: t('Common.unprocessableContent'),
Should the error message be more precise to indicate that the error happened because dates are missing/in wrong format?

2024-04-12 11:17 UTC, erjavaskivuori commented on src/app/api/course/statistics/route.test.ts
The tests are otherwise looking good, but in my opinion it should be also tested what happens if the search params are not correct or they are missing. In the route.ts the dates given as search params are validated (with "if (!fromDate || !toDate)") but this is not tested to be working.

2024-04-15 09:33 UTC, laurelcrelia commented on src/app/api/course/statistics/route.ts
> +        message: t('Common.unprocessableContent'),
This has been implemented in [Test missing search params](https://github.com/ohtutraininghub/traininghub/pull/574/commits/9260d534c46fd6143b92572b200e2fb147ffb999) commit.

2024-04-15 10:52 UTC, erjavaskivuori approved these changes
Looks good to me! :shipit:

2024-04-15 10:52 UTC, merged